version: '3'

services:
  lavalink:
    image: fredboat/lavalink:master
    container_name: lavalink-container
    restart: unless-stopped
    networks:
      - net
    volumes:
      - ./lavalink/application.yml:/opt/Lavalink/application.yml:ro

  bot:
    build: .
    container_name: bot-container
    restart: unless-stopped
    environment:
      - DOCKER_LAVALINK_HOST=lavalink
    depends_on:
      - lavalink
    networks:
      - net

networks:
  net: